//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "projects")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub owner_id: Uuid,
	pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::tasks::Entity")]
	Tasks,
}

impl Related<super::tasks::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Tasks.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
