[package]
name = "gen-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# -- App Crates
lib-utils = { path = "../../libs/lib-utils" }
# -- Others
rand = "0.8"
anyhow = "1" # Ok for tools/
